apiVersion: v1
kind: Namespace
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/iam-veeramalla/gitops.git?ref=main
  creationTimestamp: null
  name: stage
spec: {}
status: {}
